### ISSUE TITLE
Comprehension of a method in core/src/main/java/de/pxav/kelp/core/reflect/ReflectionUtil.java

### ISSUE THREAD

**Issue by 129124** [PXAV/kelp#22]
Hi there, when I was reading the code of the function "public Object getValue(Object object, String fieldName)" in core/src/main/java/de/pxav/kelp/core/reflect/ReflectionUtil.java, I found it has no Javadoc. My understanding is “get  value of the specified field @param object the object whose field should be  extracted from the object". Can you please check if this is correct? Thanks.

**Comment by PXAV** [comment]
Hey!
Sorry for the missing JavaDoc. I am trying my best to document as much and as detailed as possible, but some classes are still not documented though.

The [`#getValue`](https://github.com/PXAV/kelp/blob/master/core/src/main/java/de/pxav/kelp/core/reflect/ReflectionUtil.java#L12) method from the ReflectionUtils basically accesses a field of an object, which has no accessor for that purpose. This is important for packet handling (NPCs, entities, etc.) as well as working with other NMS classes that have lots of private fields that are essential to execute certain operations. 

The `object` parameter is - as you already pointed out - the object in which the field you want to access is located, while `fieldName` is the name of the field. This name is case sensitive. The return value is the actual value of the field and can be cast to the expected data type (including primitives). If the field could not be found or any other error occurred, `null` will be returned.

Documentation for this class will follow in one of the next releases. If you have further questions, feel free to ask them.
Kind regards
PXAV

**Comment by 129124** [comment]
Thanks for your reply. Actually, we are working to generte the method comment automatically, and the comment provided above is our result. we would like to generate more of your code to supply the javadoc if possible later.

**Comment by Paul2708** [comment]
How do you generate JavaDoc automatically?
Do you consider the actual usage of the method? In my opinion, JavaDoc should state _why_ the method is required and not _what_ the method does, because this should be obvious by regarding name and parameters.

**Comment by PXAV** [comment]
I think a JavaDoc comment should always include information about _what_ the method does, because sometimes - especially when writing a spigot-related project - words used in method names are not directly understandable by a person who is not that much into spigot development. 

Of course, a machine cannot generate as useful comments as the actual developer, but I like the idea of JavaDoc automation because sometimes describing parameter names, etc. feels kinda redundant. If a developer proofreads the generated comments and adds some information if needed, the development process would still be speeded up a lot.
