### ISSUE TITLE
Please provide JavaDoc

### ISSUE THREAD

**Issue by Trqhxrd** [PXAV/kelp#42]
**Is your feature request related to a problem? Please describe.**
You project is self explainatory for the most part, but if you're new to it, you might want to be able fo look into the funktion of some modules. No pressure tho. If that's not possible, because the project is already to big or something, just close this feature request.
Kind regards, 
Trqhxrd

**Comment by PXAV** [comment]
Thank you for the comment, you are right there are still a lot of classes that have no JavaDocs. As I am currently the only maintainer of this project I have to balance feature enrichment, the developer Wiki and code documentation. On every release, the most important API classes should be documented so that you get enough information when coding a plugin, but other classes will follow over time. I don't think that a project can become too big to document, so there will be at least a 90% documentation coverage on the 1.0 release at the latest I think.
