### ISSUE TITLE
Provide issues

### ISSUE THREAD

**Issue by Paul2708** [PXAV/kelp#6]
Hey,
will you accept contributions?
And if so, could you provide some issues like bugs, features, ideas etc. to work on? :D

Greetings

**Comment by QetzDev** [comment]
Yeah, he do. He wrote more in the wiki.

Dear greetings.

**Comment by PXAV** [comment]
Hey Paul,

yes I am happy about contributions and people helping to develop Kelp :D Since there are no bugs to fix yet, as none have been reported, there are mainly new features that have to be implemented.

I am currently working on polishing the InventorySystem. If you want to, you could start with the Kelp Particle engine. I have created a GitHub-project board for this, containing things that have to be done. Please give feedback, if you will start working on it or have any further questions :D

(To contribute it's important to compile the needed CraftBukkit files with the official BuildTools.jar (1.8 and 1.14 are enough for now). A tutorial about that is linked in the README file. For legal reasons I am not allowed to distribute them :c)

Greetings, pxav :)

**Comment by PXAV** [comment]
Since there have been no replies for quite a while now, I'll close this issue. You can reopen it at any time if there is something to add :)
